name: "FAP: Build for multiple SDK sources"
on: 
  push:
    branches: 
      - master
  pull_request:
  schedule:
    - cron: "1 1 * * *"

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev channel
            source: official
            sdk-channel: dev
          - name: release channel
            source: official
            sdk-channel: release
          - name: Unleashed dev
            source: unleashed
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: dev
          - name: Unleashed dev
            source: unleashed
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: release
    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          sdk-index-url: ${{ matrix.sdk-index-url }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.source }}-api${{ steps.build-app.outputs.api-version }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
