name: build

on:
  push:
    branches: [ 420 ]
  pull_request:
    branches: [ 420 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build resources and icons
        run: ./fbt resources icons

      - name: build updater package
        run: ./fbt updater_package FIRMWARE_APP_SET=no_games

      - name: zip updater package
        run: cd dist/f7-C/f7-update-RM420 && zip ${{ github.sha }}.zip *

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: dist/f7-C/f7-update-RM420/${{ github.sha }}.zip
