name: build

on:
  push:
    branches: [ 420 ]
  pull_request:
    branches: [ 420 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build updater package
        run: ./fbt updater_package

      - name: zip updater package
        run: cd dist/f7-C/f7-update-RM420FAP && zip ${{ github.sha }}.zip *

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: dist/f7-C/f7-update-RM420FAP/${{ github.sha }}.zip
          
      - name: prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          body_path: ReadMe.md
          files: dist/f7-C/f7-update-RM420FAP/${{ github.sha }}.zip
